[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "rustos-target-x86-64.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
